### ISSUE TITLE
it gives error: Document number hash mismatch

### ISSUE THREAD

**Issue by yahyomas** [olexale/mrz_parser#6] opened 2021-02-03 06:39 UTC
I am pretty sure that I am entering correct data, but it says that Document number hash mismatch

**Comment by foxanna** [comment] 2021-03-02 06:37
Hi @yahyomas, 
Without a specific example of input data and expected result there is nothing we can help you with.
Please provide more information about your problem.

**Comment by olexale** [comment] 2021-04-22 09:30
closing this issue. feel free to re-open it if the issue is still relevant.

**Closed as completed by olexale** 2021-04-22 09:30 UTC
